install! 'cocoapods', :deterministic_uuids => false

inhibit_all_warnings!
use_frameworks!
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'OLScriptMessage_Example' do

	pod 'OLScriptMessage', :path => '../'
	pod 'SnapKit'

	target 'OLScriptMessage_Tests' do
		inherit! :search_paths
#		pod 'Quick', '~> 1.2.0'
#		pod 'Nimble', '~> 7.0.2'
	end
end
