install! 'cocoapods', :deterministic_uuids => false

inhibit_all_warnings!
use_frameworks!
platform :ios, '9.0'

target 'OLScriptMessage_Example' do
  pod 'OLScriptMessage', :path => '../'
  
  pod 'SnapKit'

  target 'OLScriptMessage_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0.2'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
